language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
before_script:
- npm install -g jasmine-node
deploy:
  provider: heroku
  api_key:
    secure: irJD56uwWDja4LdS8gqe4wiKNnIkleJWwsrilLVwStlh76JbmCvOLMZQ2hycl3lCaNALP/tB+L4jq9oIjrOFokmy5nGKGQjWYLYxdoOrMXdy9Qi878epQyTSBgvTxMhcuuv9idzKTsJ/59DSzHIzf+5q4EvAYnjMH8myjprD7d4=
  app: nodejs-cloud-ci
  on:
    repo: kendaleiv/nodejs-cloud-ci
    node: '0.11'
